### ISSUE TITLE
Content migration

### ISSUE THREAD

**Issue by n0rdlicht** [opensource-construction/website#6]
Migrate existing content from opensource.construction

- [x] faqs
  - [x] What is open source?
  - [x] Why open source?
  - [x] Can open source tools be used free of charge?
- [x] projects as `content/projects/${project-slug}.mdx` 
  - [x] Speckle ([live version](https://www.opensource.construction/projects/speckle/), [preview version](https://next.opensource.construction/projects/speckle/))
  - [x] [LCAx and EPDx](https://github.com/opensource-construction/website/pull/31) ([live version](https://www.opensource.construction/projects/lcax-and-epdx/))
  - [x] [BlenderBIM Add-on](https://github.com/opensource-construction/website/pull/31) ([live version](https://www.opensource.construction/projects/blenderbim-add-on/))
  - [x] [IFC Model Checker](https://github.com/opensource-construction/website/pull/31) ([live version](https://www.opensource.construction/projects/ifc-model-checker/))
  - [x] [Compas](https://github.com/opensource-construction/website/pull/31) ([live version](https://www.opensource.construction/projects/ifc-model-checker-2/))
  - [x] [vyssuals](https://github.com/opensource-construction/website/pull/31) ([live version](https://www.opensource.construction/projects/vyssuals/))
  - [x] [Circular Construction Co-Pilot](https://github.com/opensource-construction/website/pull/32) ([live version](https://www.opensource.construction/projects/circular-construction-co-pilot/))
- [ ] events as `content/events/${event-date}-${event-slug}.mdx`
  - [x] [COMPAS Developer Day](https://github.com/opensource-construction/website/pull/28) ([live version](https://www.opensource.construction/events/compas-developer-day/))
    - [x] Sign-Up Form, blocked by #22
  - [x] [Open Source in AEC – Copenhagen Event](https://github.com/opensource-construction/website/blob/main/content/events/20240423-open-source-in-aec-copenhagen-event.mdx) - [live version](https://www.opensource.construction/events/open-source-in-aec-copenhagen-event/), [preview version](https://next.opensource.construction/events/open-source-in-aec-copenhagen-event/)
  - [x] AEC Hackathon – Zurich Edition - [live version](https://www.opensource.construction/events/aec-hackathon-zurich-edition-2/)
  - [x] [DINAcon](https://github.com/opensource-construction/website/pull/30) - [live version](https://www.opensource.construction/events/dinacon/)
  - [x] [Future of Construction 2023 Symposium](https://github.com/opensource-construction/website/pull/30) - [live version](https://www.opensource.construction/events/future-of-construction-2023-symposium/)
  - [x] [Workshoptage CH Open](https://github.com/opensource-construction/website/pull/30) - [live version](https://www.opensource.construction/events/workshoptage-ch-open/)
  - [x] [Open Source in der Architektur (german)](https://github.com/opensource-construction/website/pull/30) - [live version](https://www.opensource.construction/events/open-source-in-der-architektur/)
    - [ ] Gallery: Impressions - [live version](https://www.opensource.construction/open-source-in-der-architektur/), blocked by #25
  - [x] Open Innovation Workshop «Construction & Data Science» - [live version](https://www.opensource.construction/events/open-innovation-workshop-construction-data-science/)
    - [x] Gallery: Impressions - [live version](https://www.opensource.construction/en/ruckblick-data-science-construction/), blocked by #25
  - [x] [Open Source for Architects Conference](https://github.com/opensource-construction/website/blob/main/content/events/20230316-open-source-for-architects-conference.mdx) - [live version](https://www.opensource.construction/events/open-source-for-architects-conference/), [preview version](https://next.opensource.construction/events/open-source-for-architects-conference/)
  - [x] [AEC Hackathon Copenhagen](https://github.com/opensource-construction/website/blob/main/content/events/20230303-aec-hackathon-copenhagen.mdx) - [live version](https://www.opensource.construction/events/aec-hackathon-copenhagen/), [preview version](https://next.opensource.construction/events/aec-hackathon-copenhagen/)
    - [x] Gallery: Impressions - [live version](https://photos.google.com/share/AF1QipPFTw5MyOUAnRaq1h-lYKp9V3WJivUBwGQHsFJkPu7K1_Ln8luFTCwgxYlr0KAVpw?key=S3RoekJkY0JzYnY3ODN4WUxRTkpkcGprMGVKMVRn), blocked by #25
  - [x] [Kick-Off Event opensource.construction](https://github.com/opensource-construction/website/blob/main/content/events/20231101-kick-off-event-opensource-construction.mdx) - [live version](https://www.opensource.construction/events/kick-off-event-opensource-construction/), [preview version](https://next.opensource.construction/events/kick-off-event-opensource-construction/)
    - [x] Gallery: Impressions - [live version](https://www.opensource.construction/rueckblick/), blocked by #25

**Comment by MaximilianVomhof** [comment]
Gallery Open Source in der Architektur: https://drive.google.com/file/d/14pFi9vAwXEtnuklz4I-W-e99vH0Y1QoG/view?usp=sharing

Gallery Open Innovation Workshop "Construction & Data Science": https://drive.google.com/drive/folders/1STfB5csgeUijmXpOzvY9V1eC2oepFVHU?usp=sharing

AEC Hackathon Copenhagen:
https://photos.google.com/share/AF1QipPFTw5MyOUAnRaq1h-lYKp9V3WJivUBwGQHsFJkPu7K1_Ln8luFTCwgxYlr0KAVpw?key=S3RoekJkY0JzYnY3ODN4WUxRTkpkcGprMGVKMVRn

Kick-Off Event:
https://drive.google.com/drive/folders/1STfB5csgeUijmXpOzvY9V1eC2oepFVHU?usp=sharing

AEC Hackathon Zurich:
https://drive.google.com/drive/folders/1STfB5csgeUijmXpOzvY9V1eC2oepFVHU?usp=sharing
